jdbcUrl=jdbc:oracle:thin:@localhost:1521:orcl
username=practice
password=1234

driverClassName=oracle.jdbc.driver.OracleDriver

maximumPoolSize=10
minimumIdle=5
connectionTimeout=30000
idleTimeout=600000
maxLifetime=1800000